### PR TITLE
Revert "Lesson -1.7 Assginment"

### PR DESCRIPTION
**Pull request by Wasistanikzai**
Reverts Wasistanikzai/react-app#7

### CODE REVIEW

**Review by mogulafric — CHANGES_REQUESTED** [review]
Hi,trust this is lesson 7. On Asynchronous,promise and conditional rendering.

The concepts are not well implemented. If you would like 1-1 session to review the exercise alert me on  slack. (At least a day before because of time difference)

**Comment by Wasistanikzai** [comment]
Hello, mogulafric,

I didn't find your user on slack if possible share the user to arrange the one-to-one mention regarding lession1.7 assignments. 
Thanks

**Comment by Wasistanikzai** [comment]
> Hi,trust this is lesson 7. On Asynchronous,promise and conditional rendering.
> 
> The concepts are not well implemented. If you would like 1-1 session to review the exercise alert me on slack. (At least a day before because of time difference)

Hello, mogulafric,

I didn't find your user on slack if possible share the user to arrange the one-to-one mention regarding lession1.7 assignments.
Thanks

**Review by leo-mutuku — APPROVED** [review]
API simulation well implemented using promise. Conditional rendering well implemented

**Pull request merged**
